/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoAlumnos.Presentacion;

import javax.swing.JOptionPane;
import static proyectoAlumnos.Presentacion.Globales.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio AB
 */
public class frmReporteAlumno extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    String nombreColumnas[] = {"Codigo", "Apellidos", "Nombre", "Carrera", "Ciclo", "Promedio", "Estado"};

    public frmReporteAlumno() {
        initComponents();
        this.setLocationRelativeTo(this);
        modelo.setDataVector(LP.devuelveDatos(), nombreColumnas);
        tblMostrar.setModel(modelo);
    }
public void limpiar(){
      buttonGroup1.clearSelection();
      txtbuscar.setText("");
      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new com.icm.components.metro.TableMetroICM();
        labelMetroICM1 = new com.icm.components.metro.LabelMetroICM();
        txtbuscar = new org.edisoncor.gui.textField.TextFieldRectBackground();
        buttonPopup1 = new org.edisoncor.gui.button.ButtonPopup();
        buttonAqua1 = new org.edisoncor.gui.button.ButtonAqua();
        jPanel1 = new javax.swing.JPanel();
        checAprovados = new com.icm.components.metro.CheckBoxMetroICM();
        checDesaprovados = new com.icm.components.metro.CheckBoxMetroICM();
        btnTodos = new org.edisoncor.gui.button.ButtonPopup();
        btnTodos1 = new org.edisoncor.gui.button.ButtonPopup();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNice1.setBackground(new java.awt.Color(0, 255, 0));
        panelNice1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vista Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelNice1.setForeground(new java.awt.Color(51, 255, 153));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMostrar);

        panelNice1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 740, 290));

        labelMetroICM1.setText("BUSCAR:");
        labelMetroICM1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        panelNice1.add(labelMetroICM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        txtbuscar.setDescripcion("Ingrese lo que Desea Buscar");
        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        panelNice1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 250, 40));

        buttonPopup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoAlumnos/File/icons8_Detective_30px.png"))); // NOI18N
        buttonPopup1.setText("Buscar");
        buttonPopup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPopup1ActionPerformed(evt);
            }
        });
        panelNice1.add(buttonPopup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        buttonAqua1.setBackground(new java.awt.Color(255, 255, 255));
        buttonAqua1.setBorder(null);
        buttonAqua1.setForeground(new java.awt.Color(204, 204, 204));
        buttonAqua1.setText("Salir");
        buttonAqua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua1ActionPerformed(evt);
            }
        });
        panelNice1.add(buttonAqua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checAprovados.setText("Aprovados");
        checAprovados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checAprovadosActionPerformed(evt);
            }
        });
        jPanel1.add(checAprovados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        checDesaprovados.setText("Desaprovados");
        checDesaprovados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checDesaprovadosActionPerformed(evt);
            }
        });
        jPanel1.add(checDesaprovados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        btnTodos.setText("Mostrar");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 30));

        panelNice1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 410, 50));

        btnTodos1.setText("VIEW");
        btnTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodos1ActionPerformed(evt);
            }
        });
        panelNice1.add(btnTodos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAqua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua1ActionPerformed
        dispose();
        FrmAlumnos a = new FrmAlumnos();
        a.setVisible(true);
    }//GEN-LAST:event_buttonAqua1ActionPerformed

    private void buttonPopup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPopup1ActionPerformed
        String carrera = txtbuscar.getText();
        modelo.setDataVector(LP.buscarCarrea(carrera).devuelveDatos(), nombreColumnas);
        limpiar();
    }//GEN-LAST:event_buttonPopup1ActionPerformed

    private void checAprovadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checAprovadosActionPerformed

    }//GEN-LAST:event_checAprovadosActionPerformed

    private void checDesaprovadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checDesaprovadosActionPerformed
        

    }//GEN-LAST:event_checDesaprovadosActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
   
            if (checAprovados.isSelected()) {
                String estado = "Aprovado";
               
                modelo.setDataVector(LP.alumnosAprobados(estado).devuelveDatos(), nombreColumnas);
                
            } else if (checDesaprovados.isSelected()) {
                String estado = "Desaprovado";
               modelo.setDataVector(LP.alumnosdesAprobados(estado).devuelveDatos(), nombreColumnas);
              
            } else {
               
                JOptionPane.showMessageDialog(null, "Debes Selecionar");
            }
         limpiar();
        


    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodos1ActionPerformed
       modelo.setDataVector(LP.devuelveDatos(), nombreColumnas);
    }//GEN-LAST:event_btnTodos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonPopup btnTodos;
    private org.edisoncor.gui.button.ButtonPopup btnTodos1;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua1;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.edisoncor.gui.button.ButtonPopup buttonPopup1;
    private com.icm.components.metro.CheckBoxMetroICM checAprovados;
    private com.icm.components.metro.CheckBoxMetroICM checDesaprovados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.icm.components.metro.LabelMetroICM labelMetroICM1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private com.icm.components.metro.TableMetroICM tblMostrar;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtbuscar;
    // End of variables declaration//GEN-END:variables
}
